services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/web-wallet
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm start

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
